// Local clips: CC0, one Pixabay gas strut, and a labelled user-supplied edit.
// Provenance and edit recipes: assets/obs/audio/CREDITS.md.
export const CABIN_SOUNDS=Object.freeze({
  hatchAlarm:{file:'factory-warning-buzzer.wav',label:'非常警報 / ハッチ故障',description:'Factory Warning Buzzer / 工業用ブザー・原速3秒・故障中のみ',gain:.38,loop:true,duration:3},
  powerOn:{file:'power-on-glitch.wav',label:'船内照明 / 点灯',description:'グリッチの短い断片 / 2回のスターター＋減衰',license:'ユーザー提供素材（ライセンス未確認）',gain:.24},
  doorOpen:{file:'door-open-air-motor.wav',label:'ハッチ / 開く',description:'バシュッだけ / 短い空気圧・モーター音なし',gain:.65},
  doorClose:{file:'door-close-air-motor.wav',label:'ハッチ / 閉じる',description:'バシュッだけ / 短い空気圧・モーター音なし',gain:.58},
  bedPiston:{file:'bed-piston.wav',label:'ベッド / 蓋の開閉',description:'指定のガスストラット / 原速0.52秒・引き伸ばしなし',license:'Pixabay Content License',gain:.18,duration:.52},
  bedSlide:{file:'bed-slide.wav',label:'ベッド / 寝台のスライド',description:'実録の空圧シリンダー / 短い伸縮・1.4秒',gain:.30,duration:1.4},
  latch:{file:'latch.wav',label:'ロック / 金属ラッチ',description:'短いカチッ一発 / 二度鳴りなし・控えめ',gain:.20},
  applianceLid:{file:'appliance-lid.wav',label:'洗濯機 / 蓋を閉じる',description:'実録の扉の接触音 / 鈍いコトッ・控えめ',gain:.24},
  step1:{file:'step-metal-boots-1.wav',label:'足音 / 1',description:'実録：金属床をブーツで歩く / 控えめ・低音',gain:.20,rate:.84},
  step2:{file:'step-metal-boots-2.wav',label:'足音 / 2',description:'実録：金属床をブーツで歩く / 控えめ・低音',gain:.185,rate:.84},
  step3:{file:'step-metal-boots-3.wav',label:'足音 / 3',description:'実録：金属床をブーツで歩く / 控えめ・低音',gain:.20,rate:.84},
  ladderStep1:{file:'step-ladder-boots-1.wav',label:'マイロ / ハシゴ 1',description:'実録ブーツの接地を短く・鈍く / 金属の踏み段用',gain:.13,rate:.88},
  ladderStep2:{file:'step-ladder-boots-2.wav',label:'マイロ / ハシゴ 2',description:'実録ブーツの接地を短く・鈍く / 金属の踏み段用',gain:.12,rate:.88},
  ladderStep3:{file:'step-ladder-boots-3.wav',label:'マイロ / ハシゴ 3',description:'実録ブーツの接地を短く・鈍く / 金属の踏み段用',gain:.13,rate:.88},
  rubberStep1:{file:'step-rubber-1.wav',label:'ドロイド / ゴム底 1',description:'実録：柔らかいゴム底の接地音',gain:.30},
  rubberStep2:{file:'step-rubber-2.wav',label:'ドロイド / ゴム底 2',description:'実録：柔らかいゴム底の接地音',gain:.28},
  rubberStep3:{file:'step-rubber-3.wav',label:'ドロイド / ゴム底 3',description:'実録：柔らかいゴム底の接地音',gain:.30},
  metal:{file:'metal.wav',label:'荷物 / ハードケースの着地',description:'実録の工具箱 / 短く鈍い接地音・控えめ',gain:.20},
  servo:{file:'servo-stroke.wav',label:'ドロイド / 関節の短い駆動音',description:'実録サーボ / 0.2秒・小音量・ループなし',gain:.055},
  shower:{file:'shower.wav',label:'シャワー / 流水',gain:.35,loop:true},
  flush:{file:'flush.wav',label:'トイレ / 排水',gain:.36},
  washer:{file:'washer.wav',label:'洗濯機 / 運転',gain:.27,loop:true},
  bag:{file:'bag.wav',label:'猫餌 / 袋の扱い',gain:.24},
  kibblePour:{file:'kibble-pour.wav',label:'猫餌 / カリカリを皿へ',description:'実録の乾燥フード / 皿へ落ちるカラカラ・袋音とは別',gain:.23,loop:true},
  catMeow:{file:'cat-meow.wav',label:'ルーシー / 空腹の小さな鳴き声',description:'実録：空腹の猫 / 控えめ・たまに一声',gain:.14},
  catChirp:{file:'cat-chase-chirp.wav',label:'ルーシー / ネズミに気づく声',description:'実録の短い猫の声 / 追いかけ始めに一声',gain:.18},
  mouseSqueak1:{file:'mouse-squeak-1.wav',label:'ネズミ / 逃げる声 1',description:'実録のラット / 短く小さな鳴き声・原速',gain:.12},
  mouseSqueak2:{file:'mouse-squeak-2.wav',label:'ネズミ / 逃げる声 2',description:'別の実録テイク / 追走中にもう一声・原速',gain:.10},
  chop:{file:'chop.wav',label:'調理 / 刻む',gain:.23},
  simmer:{file:'pot-simmer.wav',label:'調理 / 鍋で煮込む',description:'実録の静かな煮込み / コトコト・原速・かき混ぜる間だけ',gain:.18,loop:true},
});
export const CABIN_AUDIO_BASE='/3D/assets/obs/audio/';
